### ISSUE TITLE
Complete Manageability Considerations

### ISSUE THREAD

**Issue by italobusi** [ietf-ccamp-wg/ietf-ccamp-optical-path-computation#10]
Add text to the Manageability Considerations section

**Comment by danielkinguk** [comment]
Initial text for "Manageability Considerations" section.  

"This document provides a method for requesting path computations for WSON and Flexi-Grid tunnels. Consideration of mechanisms to gather and collate information required for the path computations will be necessary. Furthermore, storing path computation requests and responses and triggering actions according to configured will also need to be carefully managed and secured. 

Future versions of this document will contain additional information."

**Comment by italobusi** [comment]
The text on Manageability Considerations should be updated once the document is stable.
